# Generated by Django 4.2.9 on 2026-10-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='文件SHA256')),
                ('status', models.CharField(choices=[('draft', '暂存中'), ('publishing', '发布中'), ('published', '已发布'), ('discarded', '已废弃')], default='draft', max_length=20, verbose_name='批次状态')),
                ('publishing_at', models.DateTimeField(blank=True, null=True, verbose_name='进入发布时间')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('create_count', models.PositiveIntegerField(default=0, verbose_name='新增数')),
                ('update_count', models.PositiveIntegerField(default=0, verbose_name='更新数')),
                ('conflict_count', models.PositiveIntegerField(default=0, verbose_name='冲突数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'db_table': 'wh_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(verbose_name='文件行号')),
                ('variety_name', models.CharField(max_length=20, verbose_name='品种名称')),
                ('category_name', models.CharField(blank=True, max_length=10, verbose_name='品类名称')),
                ('unit_name', models.CharField(blank=True, max_length=5, verbose_name='单位名称')),
                ('status', models.CharField(choices=[('create', '新增'), ('update', '更新'), ('conflict', '冲突'), ('error', '错误')], default='error', max_length=20, verbose_name='校验结果')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='错误信息')),
                ('published', models.BooleanField(default=False, verbose_name='是否已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='warehouse.importbatch', verbose_name='所属批次')),
                ('target_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='warehouse.variety', verbose_name='发布目标品种')),
            ],
            options={
                'verbose_name': '导入暂存行',
                'verbose_name_plural': '导入暂存行',
                'db_table': 'wh_import_row',
                'ordering': ['row_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_no'), name='uniq_import_row_no'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'publishing', 'published'])), fields=('file_hash',), name='uniq_active_import_batch_file_hash'),
        ),
    ]
