# Generated by Django 4.2.9 on 2026-10-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='文件SHA256')),
                ('status', models.CharField(choices=[('draft', '待修订'), ('ready', '待发布'), ('publishing', '发布中'), ('published', '已发布')], default='draft', max_length=20, verbose_name='批次状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('create_count', models.PositiveIntegerField(default=0, verbose_name='新增数')),
                ('update_count', models.PositiveIntegerField(default=0, verbose_name='更新数')),
                ('conflict_count', models.PositiveIntegerField(default=0, verbose_name='冲突数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误行数')),
                ('publish_error', models.TextField(blank=True, verbose_name='发布失败原因')),
                ('publish_started_at', models.DateTimeField(blank=True, null=True, verbose_name='发布开始时间')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='最近校验时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '品种导入批次',
                'verbose_name_plural': '品种导入批次',
                'db_table': 'wh_import_batch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.PositiveIntegerField(verbose_name='Excel行号')),
                ('variety_name', models.CharField(blank=True, max_length=20, verbose_name='品种')),
                ('category_name', models.CharField(blank=True, max_length=10, verbose_name='品类')),
                ('unit_name', models.CharField(blank=True, max_length=5, verbose_name='单位')),
                ('result', models.CharField(choices=[('error', '错误'), ('create', '新增'), ('update', '更新'), ('conflict', '冲突'), ('created', '已新增'), ('updated', '已更新')], default='error', max_length=20, verbose_name='校验结果')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='错误原因')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='warehouse.importbatch', verbose_name='所属批次')),
                ('published_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_import_rows', to='warehouse.variety', verbose_name='发布写入的品种')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='warehouse.variety', verbose_name='命中的正式品种')),
            ],
            options={
                'verbose_name': '品种导入暂存行',
                'verbose_name_plural': '品种导入暂存行',
                'db_table': 'wh_import_row',
                'ordering': ['sheet_row'],
                'unique_together': {('batch', 'sheet_row')},
            },
        ),
    ]
